services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=bukashki
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432" # host:container
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d bukashki" ]
      interval: 5s
      timeout: 5s
      retries: 5


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # api
      - "9001:9001" # web panel
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    hostname: kafka

    # Пробрасываем порт что бы слать в кафка сообщения с хоста
    ports:
      - "29092:29092"
    environment:
      # docker run --rm confluentinc/cp-kafka:8.1.0 kafka-storage random-uuid
      CLUSTER_ID: 9iLiYShHT7e8kZkSUuBxrA
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # PLAINTEXT - нет шифрования
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

    volumes:
      - volume:
          kafka-data: /var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./bukashki
    ports:
      - "8080:8080" # host:container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bukashki
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - MINIO_URL=http://minio:9000
      - MINIO_PUBLICURL=http://localhost:9000
      - MINIO_USERNAME=miniouser
      - MINIO_PASSWORD=miniopass
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
