spring.application.name=bukashki

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/bukashki
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=aaCFajtpo2e6mFoUrGoLrjaFFiLjF2LjVYON5hiPiO/2i5aI0PG0Ks4yGab7d7m8
jwt.expiration-ms=86400000

minio.url=http://localhost:9000
minio.public-url=http://localhost:9000
minio.username=miniouser
minio.password=miniopass
minio.bucket=bukashki
